# Generated by Django 5.2.7 on 2025-12-01 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_compteur", models.CharField(max_length=2, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taxes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redevance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxe_communale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tva_pourcentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                (
                    "type_compteur",
                    models.CharField(
                        choices=[
                            ("BT", "Basse Tension"),
                            ("MT", "Moyenne Tension"),
                            ("HT", "Haute Tension"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("kwh_obtenus", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_achat", models.DateTimeField(auto_now_add=True)),
                ("detail_simulation", models.JSONField(blank=True, null=True)),
                (
                    "compteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.compteur"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tranche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField()),
                ("limite_kwh", models.PositiveIntegerField(blank=True, null=True)),
                ("prix_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="main.tarif",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ConsommationMensuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.DateField()),
                ("kwh_consumes", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "compteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.compteur"
                    ),
                ),
            ],
            options={
                "ordering": ["mois"],
                "unique_together": {("compteur", "mois")},
            },
        ),
    ]
