# Generated by Django 5.2.8 on 2025-12-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandationml',
            name='duree_vie_jours',
            field=models.IntegerField(default=0, help_text="Durée réelle, en jours, de l'électricité achetée."),
        ),
    ]
